#ifndef ORBIT_VERSION_INFORMATION_HPP
#define ORBIT_VERSION_INFORMATION_HPP

#define ORBIT_MAJOR_VERSION (0)
#define ORBIT_MINOR_VERSION (1)
#define ORBIT_PATCH_VERSION (0)
#define ORBIT_VERSION "0.1.0"

#endif  // BSLCORE_VERSION_
