[package]
name = "coal_lang"
version = "0.1.0"
authors = ["bosley <bosley117@gmail.com>"]
edition = "2018"

[build-dependencies]
lalrpop = { version="0.19.0" }

[dependencies]
derive_more = "0.99.0"
lalrpop-util = "0.19.0"
regex = "1"
rug = "1.11.0"