
'''
        This file was generated by configure.py

        slots: 
            Use slots to respond to an inquiry from
            a remote node. 

        routines:
            Routines are constantly ran to allow
            changes in a device (measurement, etc) 
            a chance to trigger an event.

            *When constructing routines, remember to return
             None if nothing happens.
'''
                    
# Generated Slots

def slot_turn_on_0(stream):
    return "_UNSET_"

def slot_turn_off_1(stream):
    return "_UNSET_"

def slot_toggle_2(stream):
    return "_UNSET_"

# Generated Routines

# Routed dictionaries
slots = {
    "turn_on": slot_turn_on_0,
    "turn_off": slot_turn_off_1,
    "toggle": slot_toggle_2,
}
routines = {}
