
'''
        This file was generated by configure.py

        slots: 
            Use slots to respond to an inquiry from
            a remote node. 

        routines:
            Routines are constantly ran to allow
            changes in a device (measurement, etc) 
            a chance to trigger an event.

            *When constructing routines, remember to return
             None if nothing happens.
'''

from random import randint

# Generated Slots

# Generated Routines


#
#       This is where we would place gpio reading and send data up
#
#
def routine_check_motion_0():
    
    # 50% of the time there will be motion
    if randint(1,2) == 1:
        return True
    else:
        return False

# Routed dictionaries
slots = {}
routines= {
    "check_motion": routine_check_motion_0,
}