
'''
        This file was generated by configure.py

        slots: 
            Use slots to respond to an inquiry from
            a remote node. 

        routines:
            Routines are constantly ran to allow
            changes in a device (measurement, etc) 
            a chance to trigger an event.

            *When constructing routines, remember to return
             None if nothing happens.
'''
                    
# Generated Slots

def slot_get_temp_0(stream):
    
    return 72

# Generated Routines

def routine_check_for_overheat_0():
    return None

# Routed dictionaries
slots = {
    "get_temp": slot_get_temp_0,
}
routines= {
    "check_for_overheat": routine_check_for_overheat_0,
}
