
//#define CTCPLIB_DEBUG 1

#define CTCPLIB_LISTEN_BACKLOG 10

#define CTCPLIB_STD_CHUNK_TELL 10
#define CTCPLIB_STD_CHUNK_SIZE 100 // Turn this to 1024

#define CTCPLIB_STD_REPLY_SIZE 20

#define CTCPLIB_STD_REPLY_CONFIRM "[RECEIPT_CONFIRM]"
#define CTCPLIB_STD_REPLY_DENY    "[REQUEST_DENIED]"
