[package]
name = "micron_parser"
version = "0.1.0"
authors = ["bosley <bosley117@gmail.com>"]
edition = "2018"

[build-dependencies]
lalrpop = { version="0.19.0", features = ["lexer"] }

[dependencies]
lalrpop-util = "0.19.0"
regex = "1"
rug = "1.11.0"

micron_ast = { path = "../ast" }